create table if not exists customers
(
    id         bigint primary key generated by default as identity,
    first_name varchar(50)   not null,
    last_name  varchar(100)  not null,
    address    varchar(1000) not null,
    budget     decimal       not null
);
insert into customers
VALUES (1, 'Tom', 'Tomson', 'NoRF', 1000.00);